apiVersion: batch/v1
kind: Job
metadata:
  generateName: init-job-
  annotations:
    helm.sh/hook: post-install
spec:
  template:
    spec:
      containers:

      - name: init
        image: alpine
        args:
        - /bin/sh
        - -ec
        - "echo Running!"
      restartPolicy: Never
  backoffLimit: 4
